version: '3'

services:
  loadbalancer:
    build:
      context: ../load-balancer
      dockerfile: Dockerfile
    depends_on:
      - web
    container_name: loadbalancerdocker
    ports:
      - "8080:6000"
  web:
    image: logservicedocker
    build:
      context: ../LogService
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "35001:6000"
  web2:
    image: logservicedocker
    container_name: service2
    depends_on:
      - db
    ports:
      - "35002:6000"
  web3:
    image: logservicedocker
    container_name: service3
    ports:
      - "35003:6000"
  db:
    image: mongo:latest
    container_name: mongo-docker-database
    environment:
      MONGO_INITDB_DATABASE: LabArepDocker
      MONGO_INITDB_ROOT_USERNAME: andres
      MONGO_INITDB_ROOT_PASSWORD: 12345asdSS
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

    command: mongod

volumes:
  mongodb:
  mongodb_config:
